# Generated by Django 5.0.4 on 2024-08-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='upi_id',
            field=models.IntegerField(default=0),
        ),
    ]
